#!/bin/sh
#
# This hook reminds students to only use their own branches
# based on username
#
# to install, rename this file like so:
# mv git-hooks-pre-commit .git/hooks/pre-commit

branch=`git rev-parse  --abbrev-ref=strict HEAD`
cutbranch=`echo $branch | cut -d \- -f 1`
student=`whoami`
if test "$cutbranch" != "$student"
then
  echo "Branch name needs to be $student-[project], current branch is $branch."
  exit 1
fi
